# pool: 'Hosted Ubuntu 1604'
pool: 'Hosted VS2017'

variables:
- name: managementGroupId
  value: root
- name: blueprintName
  value: 101-boilerplate
- name: spnId
  value: 'a50a4137-5dfa-4fe7-b283-4639e27b2119'
- name: subscriptionId
  value: 'd56e652e-758d-480a-8f0d-47f230264b4c'
- name: tenantId
  value: '220caee9-352a-4eb3-80eb-cc1dabf7be3c'
- group: azureLoginDetails

trigger:
  branches:
    include:
    - master
  paths:
    exclude:
    - README.md
    - LICENSE
    - .gitignore
    - .github/*

steps:

 - task: PowerShell@2
   displayName: 'Push new draft definition, publish -test version'
   inputs:
     targetType: 'filePath'
     filePath: '.\pipelines-scripts\build.ps1'
     arguments: '-mgId $(managementGroupId) -BlueprintFolder "$(Build.SourcesDirectory)\samples\$(blueprintName)" -blueprintName $(blueprintName) -spnId $(spnId) -spnPass $(spnPass) -tenantId $(tenantId)'
     errorActionPreference: 'stop'

 - task: PowerShell@2
   displayName: 'Assign test version, validate, and publish .stable version'
   inputs:
     targetType: 'filePath'
     filePath: '..\pipelines-scripts\release.ps1'
     arguments: '-subId $(subscriptionId) -blueprintName $(blueprintName) -spnId $(spnId) -spnPass $(spnPass) -tenantId $(tenantId) -mgId $(managementGroupId)'
     errorActionPreference: 'stop'

